#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1

traits:
    - securedBySteroidsApiKey:
        headers:
          steroidsApiKey:
            type: string
            example: exampleapikey
            default: f6745c13e024ef2f764b4512b0be46af5e79d5af9f82c3e51144425166bd55d7
          steroidsAppId:
            type: integer
            example: 1234
            default: 84206
  
schemas:
  - Recipe_collection: '{"$schema":"http://json-schema.org/schema","title":"Recipe collection","type":"object","properties":{"results":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Recipe representation","properties":{"actions":{"type":"string"},"author":{"type":"string"},"createdAt":{"type":"string"},"description":{"type":"string"},"image":{"type":"object"},"ingredients":{"type":"string"},"name":{"type":"string"},"objectId":{"type":"string"},"time":{"type":"string"},"updatedAt":{"type":"string"},"uuid":{"type":"string"}},"required":[]}}}}'
  - Recipe_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Recipe representation","properties":{"actions":{"type":"string"},"author":{"type":"string"},"createdAt":{"type":"string"},"description":{"type":"string"},"image":{"type":"object"},"ingredients":{"type":"string"},"name":{"type":"string"},"objectId":{"type":"string"},"time":{"type":"string"},"updatedAt":{"type":"string"},"uuid":{"type":"string"}},"required":[]}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:

  - parse_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "results"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - parse_member:
      usage: This resourceType should be used for any parse item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/Recipe:
  description: |
    {
      "resourceName": "Recipe",
      "identifierKey": "objectId"
    }
  type: parse_collection
  /{id}:
    type: parse_member


